default_platform(:mac)

lane: setup do 
  create_keychain(
    name: "fastlane_match_code_sign",
    password: ENV["KEYCHAIN_PASSWORD"],
    default_keychain: false,
    unlock: true,
    timeout: 3600,
    lock_when_sleeps: false
  )
end

lane :certificates do
  match(
    app_identifier: [
      "com.wendyliga.mimiq", 
      "com.wendyliga.mimiq-helper"
    ],
    type: "developer_id",
    readonly: true
  )
end

lane :release do 
  certificates()
  # sh "./code_sign.sh"

  build_mac_app(
      project: "mimiq.xcodeproj",
      scheme: "mimiq",
      skip_package_pkg: true,
      clean: true,
      silent: true,
      export_method: "developer-id"
  )

  notarize(
    package: ".build/output/mimiq.app",
    asc_provider: ENV["TEAM_ID"],
    print_log: true,
    verbose: true
  )
end