name: Release

# on:
#   push:
#     tags:
#       - '*'

on:
  pull_request:
    branches: [master]
    types: [synchronize, opened, reopened, ready_for_review]

jobs:
  upload_binary:
    name: Notarize Binary
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Bundler
      run: |
        sudo gem install bundler
        bundle update --bundler
    - name: Update Bundler
      run: bundle install
    - name: Notarize
      run: bundle exec fastlane release
      env:
        MATCH_REPO: ${{ secrets.FASTLANE_CODE_SIGN_REPO_URL }}
        MATCH_PASSWORD: ${{ secrets.FASTLANE_MATCH_PASSPHRASE }}
        MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.FASTLANE_MATCH_GIT_BASIC_AUTHORIZATION }}
        GIT_EMAIL: ${{ secrets.FASTLANE_CODE_SIGN_REPO_USER }}
        APPLE_ID: ${{ secrets.APPLE_ID }} 
        FL_NOTARIZE_PASSWORD : ${{ secrets.APPLE_ACCESS_TOKEN }}
        FASTLANE_PASSWORD: ${{ secrets.APPLE_ACCESS_TOKEN }}
        TEAM_NAME: ${{ secrets.TEAM_NAME }} 
        TEAM_ID: ${{ secrets.TEAM_ID }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }} 